#!/bin/bash

NAME[1]="Albee"
NAME[21]="Anastasi"
NAME[2]="Clark"
NAME[24]="Fordney-Settlage"
NAME[26]="Fryer"
NAME[3]="Gebhard"
NAME[5]="Gold"
NAME[23]="Kameny"
NAME[8]="Gittings"
NAME[6]="Milgram"
NAME[27]="Piaget"
NAME[2]="Tyler"
NAME[7]="Spitzer"
NAME[8]="Szasz"
NAME[4]="Zimbardo"
NAME[19]="Green"
NAME[20]="Hopcke"
NAME[14]="Leif"
NAME[15]="Socarides"
NAME[22]="Bieber"
NAME[16]="Marmor"
NAME[17]="Spiegel"
NAME[9]="Bandura"
NAME[13]="Harlow"
NAME[11]="Hooker"
NAME[18]="Chomsky"
NAME[10]="Marr"
NAME[12]="Miller"

echo "Source,Target,Type,Id,Lable,Weight"


i=0
hardcount=0
for file in `ls -1 ./CharacterSheets.scriv/files/docs/*.rtf`
do
	i=$[$i +1]
	for target in "${!NAME[@]}"
	do
		COUNT=`grep -c ${NAME[$target]} $file`
	#	echo $target
		if [ $COUNT -gt 0 ] 
		then
		hardcount=$[$hardcount +1]
		echo -n $i
		echo -n ","
		echo -n $target
		echo -n ","
		echo -n "Directed,"
		echo -n $hardcount
		echo -n ","
		echo -n ","
		echo -n $COUNT
		echo
		fi
	done
done
